sudo: required
language: c

matrix:
   include:
     - env: postgres=9.2
       addons:
            postgresql: 9.2
       install:
            - sudo apt-get install postgresql-server-dev-9.2
     - env: postgres=9.3
       addons:
            postgresql: 9.3
       install:
            - sudo apt-get install postgresql-server-dev-9.3
     - env: postgres=9.4
       addons:
            postgresql: 9.4
       install:
            - sudo apt-get install postgresql-server-dev-9.4
     - env: postgres=9.5
       addons:
            postgresql: 9.5
       install:
            - sudo apt-get install postgresql-server-dev-9.5
     - env: postgres=9.6
       addons:
            postgresql: 9.6
       install:
            - sudo apt-get install postgresql-server-dev-9.6
     - env: postgres=10
       addons:
            postgresql: 10
       install:
            - sudo /etc/init.d/postgresql stop
            - wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
            - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
            - sudo apt-get update
            - sudo apt-get install postgresql postgresql-contrib postgresql-client
            - sudo apt-get install postgresql-server-dev-10

   allow_failures:
     - env: postgres=9.2
     - env: postgres=9.3

   fast_finish: true


script:
  - bash ./travis_script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
