sudo: required
language: c

matrix:
   include:
     - env: postgres=9.2
       addons:
            postgresql: 9.2
       install:
            - sudo apt-get install postgresql-server-dev-9.2
     - env: postgres=9.3
       addons:
            postgresql: 9.3
       install:
            - sudo apt-get install postgresql-server-dev-9.3
     - env: postgres=9.4
       addons:
            postgresql: 9.4
       install:
            - sudo apt-get install postgresql-server-dev-9.4
     - env: postgres=9.5
       addons:
            postgresql: 9.5
       install:
            - sudo apt-get install postgresql-server-dev-9.5
     - env: postgres=9.6
       addons:
            postgresql: 9.6
       install:
            - sudo apt-get install postgresql-server-dev-9.6
     - env: postgres=10
       addons:
            postgresql: 10
       install:
            - sudo apt-get install postgresql-10 postgresql-client-10 postgresql-server-dev-10
            - export PGPORT=5433

   allow_failures:
     - env: postgres=9.2
     - env: postgres=9.3

   fast_finish: true


script:
  - bash ./travis_script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
