BEGIN;
-- binary_copy should copy data binary from country;
-- ./spec/binary_copy_spec.rb:22;
CREATE EXTENSION istore;
CREATE TABLE before (a istore);
INSERT INTO before values ('"1"=>"1"'),('"1"=>"2"'),('"1"=>"3"'),('"2"=>"1"'),('"2"=>NULL'),('"2"=>"2"');
CREATE TABLE after (a istore);
COPY before TO '/tmp/tst' WITH (FORMAT binary);
COPY after FROM '/tmp/tst' WITH (FORMAT binary);
SELECT * FROM after;
ROLLBACK;
