BEGIN;
-- cistore should pass valid cistores;
-- ./spec/cistore_test_spec.rb:8;
CREATE EXTENSION istore;
SELECT 'de::phone::ios=>25,us::phone::ios=>10'::cistore;
SELECT 'de::phone::ios::10=>25,us::phone::ios::1=>10'::cistore;
SELECT cistore('de'::country, 'phone'::device_type, 'ios'::os_name, 10);
SELECT cistore('de'::country, 'phone'::device_type, 'ios'::os_name, 5::smallint, 10::bigint);
SELECT 'de::phone::ios::10=>25,us::phone::ios::1=>10'::cistore + 'de::tablet::ios::10=>25,us::phone::ios::1=>10'::cistore;
ROLLBACK;
