BEGIN;
-- functions_plain should find keys with exists;
-- ./spec/functions_plain_spec.rb:8;
CREATE EXTENSION istore;
SELECT exist('1=>1'::istore, 1);
SELECT exist('1=>1'::istore, 2);
SELECT exist('1=>1, -1=>0'::istore, 2);
SELECT exist('1=>1, -1=>0'::istore, -1);
ROLLBACK;
BEGIN;
-- functions_plain should fetchvals;
-- ./spec/functions_plain_spec.rb:15;
CREATE EXTENSION istore;
SELECT fetchval('1=>1'::istore, 1);
SELECT fetchval('2=>1'::istore, 1);
SELECT fetchval('1=>1, 1=>1'::istore, 1);
SELECT fetchval('1=>1, 1=>1'::istore, 2);
ROLLBACK;
BEGIN;
-- functions_plain should add istores;
-- ./spec/functions_plain_spec.rb:22;
CREATE EXTENSION istore;
SELECT add('1=>1, 2=>1'::istore, '1=>1, 2=>1'::istore);
SELECT add('1=>1, 2=>1'::istore, '-1=>1, 2=>1'::istore);
SELECT add('1=>1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT add('-1=>1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT add('-1=>-1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT add('-1=>-1, 2=>1'::istore, 1);
SELECT add('-1=>-1, 2=>1'::istore, -1);
SELECT add('-1=>-1, 2=>1'::istore, 0);
ROLLBACK;
BEGIN;
-- functions_plain should substract istores;
-- ./spec/functions_plain_spec.rb:41;
CREATE EXTENSION istore;
SELECT subtract('1=>1, 2=>1'::istore, '1=>1, 2=>1'::istore);
SELECT subtract('1=>1, 2=>1'::istore, '-1=>1, 2=>1'::istore);
SELECT subtract('1=>1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT subtract('-1=>1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT subtract('-1=>-1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT subtract('-1=>-1, 2=>1'::istore, 1);
SELECT subtract('-1=>-1, 2=>1'::istore, -1);
SELECT subtract('-1=>-1, 2=>1'::istore, 0);
ROLLBACK;
BEGIN;
-- functions_plain should multiply istores;
-- ./spec/functions_plain_spec.rb:60;
CREATE EXTENSION istore;
SELECT multiply('1=>1, 2=>1'::istore, '1=>1, 2=>1'::istore);
SELECT multiply('1=>1, 2=>1'::istore, '-1=>1, 2=>1'::istore);
SELECT multiply('1=>1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT multiply('-1=>1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT multiply('-1=>-1, 2=>1'::istore, '-1=>-1, 2=>1'::istore);
SELECT multiply('-1=>-1, 2=>1'::istore, 1);
SELECT multiply('-1=>-1, 2=>1'::istore, -1);
SELECT multiply('-1=>-1, 2=>1'::istore, 0);
ROLLBACK;
BEGIN;
-- functions_plain should generate istore from array;
-- ./spec/functions_plain_spec.rb:79;
CREATE EXTENSION istore;
SELECT istore_from_array(ARRAY[1]);
SELECT istore_from_array(ARRAY[1,1,1,1]);
SELECT istore_from_array(NULL);
SELECT istore_from_array(ARRAY[1,2,3,4]);
SELECT istore_from_array(ARRAY[1,2,3,4,1,2,3,4]);
SELECT istore_from_array(ARRAY[1,2,3,4,1,2,3,NULL]);
SELECT istore_from_array(ARRAY[NULL,2,3,4,1,2,3,4]);
SELECT istore_from_array(ARRAY[NULL,2,3,4,1,2,3,NULL]);
SELECT istore_from_array(ARRAY[1,2,3,NULL,1,NULL,3,4,1,2,3]);
ROLLBACK;
BEGIN;
-- functions_plain should agg an array of istores;
-- ./spec/functions_plain_spec.rb:99;
CREATE EXTENSION istore;
SELECT istore_agg(ARRAY['1=>1']::istore[]);
SELECT istore_agg(ARRAY['1=>1','1=>1']::istore[]);
SELECT istore_agg(ARRAY['1=>1,2=>1','1=>1,2=>-1']::istore[]);
SELECT istore_agg(ARRAY['1=>1,2=>1','1=>1,2=>-1',NULL]::istore[]);
SELECT istore_agg(ARRAY[NULL,'1=>1,2=>1','1=>1,2=>-1']::istore[]);
SELECT istore_agg(ARRAY[NULL,'1=>1,2=>1','1=>1,2=>-1',NULL]::istore[]);
ROLLBACK;
BEGIN;
-- functions_plain should sum up istores;
-- ./spec/functions_plain_spec.rb:114;
CREATE EXTENSION istore;
SELECT istore_sum_up('1=>1'::istore);
SELECT istore_sum_up(NULL::istore);
SELECT istore_sum_up('1=>1, 2=>1'::istore);
SELECT istore_sum_up('1=>1 ,2=>-1, 1=>1'::istore);
ROLLBACK;
BEGIN;
-- functions_plain should sum istores from table;
-- ./spec/functions_plain_spec.rb:121;
CREATE EXTENSION istore;
CREATE TABLE test (a istore);
INSERT INTO test VALUES('1=>1'),('2=>1'), ('3=>1');
SELECT SUM(a) FROM test;
ROLLBACK;
BEGIN;
-- functions_plain should sum istores from table;
-- ./spec/functions_plain_spec.rb:128;
CREATE EXTENSION istore;
CREATE TABLE test (a istore);
INSERT INTO test VALUES('1=>1'),('2=>1'),('3=>1'),(NULL),('3=>3');
SELECT SUM(a) FROM test;
ROLLBACK;
BEGIN;
-- functions_plain should sum istores from table;
-- ./spec/functions_plain_spec.rb:135;
CREATE EXTENSION istore;
CREATE TABLE test (a istore);
INSERT INTO test VALUES('1=>1'),('2=>1'),('3=>1'),(NULL),('3=>NULL');
SELECT SUM(a) FROM test;
ROLLBACK;
