BEGIN;
-- functions_device should find presence of a key;
-- ./spec/functions_device_spec.rb:8;
CREATE EXTENSION istore;
SELECT exist('phone=>1'::device_istore, 'phone');
SELECT exist('phone=>1'::device_istore, 'tablet');
SELECT exist('phone=>1, bot=>0'::device_istore, 'bot');
SELECT exist('phone=>1, bot=>0'::device_istore, 'kermit');
ROLLBACK;
BEGIN;
-- functions_device should fetch values;
-- ./spec/functions_device_spec.rb:15;
CREATE EXTENSION istore;
SELECT fetchval('phone=>1'::device_istore, 'phone');
SELECT fetchval('tablet=>1'::device_istore, 'phone');
SELECT fetchval('phone=>1, phone=>1'::device_istore, 'tablet');
SELECT fetchval('phone=>1, phone=>1'::device_istore, 'phone');
ROLLBACK;
BEGIN;
-- functions_device should add to device_istores;
-- ./spec/functions_device_spec.rb:22;
CREATE EXTENSION istore;
SELECT add('phone=>1, tablet=>1'::device_istore, 'phone=>1, tablet=>1'::device_istore);
SELECT add('phone=>1, tablet=>1'::device_istore, 'bot=>1, tablet=>1'::device_istore);
SELECT add('phone=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT add('bot=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT add('bot=>-1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT add('bot=>-1, tablet=>1'::device_istore, 1);
SELECT add('bot=>-1, tablet=>1'::device_istore, -1);
SELECT add('bot=>-1, tablet=>1'::device_istore, 0);
ROLLBACK;
BEGIN;
-- functions_device should substract device_istores;
-- ./spec/functions_device_spec.rb:41;
CREATE EXTENSION istore;
SELECT subtract('phone=>1, tablet=>1'::device_istore, 'phone=>1, tablet=>1'::device_istore);
SELECT subtract('phone=>1, tablet=>1'::device_istore, 'bot=>1, tablet=>1'::device_istore);
SELECT subtract('phone=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT subtract('bot=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT subtract('bot=>-1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT subtract('bot=>-1, tablet=>1'::device_istore, 1);
SELECT subtract('bot=>-1, tablet=>1'::device_istore, -1);
SELECT subtract('bot=>-1, tablet=>1'::device_istore, 0);
ROLLBACK;
BEGIN;
-- functions_device should multiply device_istores;
-- ./spec/functions_device_spec.rb:60;
CREATE EXTENSION istore;
SELECT multiply('phone=>1, tablet=>1'::device_istore, 'phone=>1, tablet=>1'::device_istore);
SELECT multiply('phone=>1, tablet=>1'::device_istore, 'bot=>1, tablet=>1'::device_istore);
SELECT multiply('phone=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT multiply('bot=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT multiply('bot=>-1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT multiply('bot=>-1, tablet=>1'::device_istore, 1);
SELECT multiply('bot=>-1, tablet=>1'::device_istore, -1);
SELECT multiply('bot=>-1, tablet=>1'::device_istore, 0);
ROLLBACK;
BEGIN;
-- functions_device should divide device_istores;
-- ./spec/functions_device_spec.rb:79;
CREATE EXTENSION istore;
SELECT divide('phone=>1, tablet=>1'::device_istore, 'phone=>1, tablet=>1'::device_istore);
SELECT divide('phone=>1, tablet=>1'::device_istore, 'bot=>1, tablet=>1'::device_istore);
SELECT divide('phone=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT divide('bot=>1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT divide('bot=>-1, tablet=>1'::device_istore, 'bot=>-1, tablet=>1'::device_istore);
SELECT divide('bot=>-1, tablet=>1'::device_istore, 1);
SELECT divide('bot=>-1, tablet=>1'::device_istore, -1);
SELECT divide('bot=>-1, tablet=>1'::device_istore, 0);
SELECT divide('bot=>-1, tablet=>1'::device_istore, 1::bigint);
SELECT divide('bot=>-1, tablet=>1'::device_istore, -1::bigint);
SELECT divide('bot=>-1, tablet=>1'::device_istore, 0::bigint);
SELECT divide('bot=>-8000000000, tablet=>8000000000'::device_istore, 4000000000);
ROLLBACK;
BEGIN;
-- functions_device should create an device_istore from array;
-- ./spec/functions_device_spec.rb:106;
CREATE EXTENSION istore;
SELECT device_istore_from_array(ARRAY['bot']);
SELECT device_istore_from_array(ARRAY['bot','bot','bot','bot']);
SELECT device_istore_from_array(NULL::text[]);
SELECT device_istore_from_array(ARRAY['bot','phone','tablet','mac']);
SELECT device_istore_from_array(ARRAY['bot','phone','tablet','mac','bot','phone','tablet','mac']);
SELECT device_istore_from_array(ARRAY['bot','phone','tablet','mac','bot','phone','tablet','mac',NULL]);
SELECT device_istore_from_array(ARRAY[NULL,'bot','phone','tablet','mac','bot','phone','tablet','mac']);
SELECT device_istore_from_array(ARRAY[NULL,'bot','phone','tablet','mac','bot','phone','tablet','mac',NULL]);
SELECT device_istore_from_array(ARRAY['bot','phone','tablet','mac','bot','phone','tablet','mac',NULL,'bot',NULL,'bot','phone','tablet','mac','bot','phone','tablet','mac']);
SELECT device_istore_from_array(ARRAY['bot'::device_type]);
SELECT device_istore_from_array(ARRAY['bot'::device_type,'bot'::device_type,'bot'::device_type,'bot'::device_type]);
SELECT device_istore_from_array(NULL::text[]);
SELECT device_istore_from_array(ARRAY['bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type]);
SELECT device_istore_from_array(ARRAY['bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type]);
SELECT device_istore_from_array(ARRAY['bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,NULL]);
SELECT device_istore_from_array(ARRAY[NULL,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type]);
SELECT device_istore_from_array(ARRAY[NULL,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,NULL]);
SELECT device_istore_from_array(ARRAY['bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,NULL,'bot'::device_type,NULL,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type,'bot'::device_type,'phone'::device_type,'tablet'::device_type,'mac'::device_type]);
SELECT device_istore_from_array(ARRAY[NULL::device_type,NULL::device_type,NULL::device_type,NULL::device_type,NULL::device_type,NULL::device_type,NULL::device_type,NULL::device_type,NULL,NULL::device_type,NULL]);
SELECT device_istore_from_array(ARRAY[]::device_type[]);
ROLLBACK;
BEGIN;
-- functions_device should agg an array of device_istores;
-- ./spec/functions_device_spec.rb:145;
CREATE EXTENSION istore;
SELECT device_istore_agg(ARRAY['phone=>1']::device_istore[]);
SELECT device_istore_agg(ARRAY['phone=>1','phone=>1']::device_istore[]);
SELECT device_istore_agg(ARRAY['phone=>1,tablet=>1','phone=>1,tablet=>-1']::device_istore[]);
SELECT device_istore_agg(ARRAY['phone=>1,tablet=>1','phone=>1,tablet=>-1',NULL]::device_istore[]);
SELECT device_istore_agg(ARRAY[NULL,'phone=>1,tablet=>1','phone=>1,tablet=>-1']::device_istore[]);
SELECT device_istore_agg(ARRAY[NULL,'phone=>1,tablet=>1','phone=>1,tablet=>-1',NULL]::device_istore[]);
ROLLBACK;
BEGIN;
-- functions_device should sum up device_istores;
-- ./spec/functions_device_spec.rb:160;
CREATE EXTENSION istore;
SELECT device_istore_sum_up('phone=>1'::device_istore);
SELECT device_istore_sum_up(NULL::device_istore);
SELECT device_istore_sum_up('phone=>1, tablet=>1'::device_istore);
SELECT device_istore_sum_up('phone=>1 ,tablet=>-1, phone=>1'::device_istore);
ROLLBACK;
BEGIN;
-- functions_device should SUM device_istores FROM table;
-- ./spec/functions_device_spec.rb:167;
CREATE EXTENSION istore;
CREATE TABLE test (a device_istore);
INSERT INTO test VALUES ('phone=>1'), ('tablet=>1'), ('mac=>1');
SELECT SUM(a) FROM test;
ROLLBACK;
BEGIN;
-- functions_device should SUM device_istores FROM table;
-- ./spec/functions_device_spec.rb:174;
CREATE EXTENSION istore;
CREATE TABLE test (a device_istore);
INSERT INTO test VALUES ('phone=>1'), ('tablet=>1'), ('mac=>1'), (NULL), ('mac=>3');
SELECT SUM(a) FROM test;
ROLLBACK;
