BEGIN;
-- isagg should be upgradeable;
-- ./spec/istore/migration_spec.rb:4;
CREATE EXTENSION istore VERSION '0.1.3';
ALTER EXTENSION istore UPDATE TO '0.1.4';
ALTER EXTENSION istore UPDATE TO '0.1.3';
SELECT e.extname, e.extversion FROM pg_catalog.pg_extension e WHERE e.extname = 'istore'ORDER BY 1;;
ROLLBACK;
BEGIN;
-- isagg should be downgradeable;
-- ./spec/istore/migration_spec.rb:12;
CREATE EXTENSION istore;;
ALTER EXTENSION istore UPDATE TO '0.1.3';;
SELECT e.extname, e.extversion FROM pg_catalog.pg_extension e WHERE e.extname = 'istore'ORDER BY 1;;
ROLLBACK;
