BEGIN;
-- operator istore should fetch values;
-- ./spec/operator_spec.rb:9;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>0'::istore -> -1;
SELECT '1=>1, -1=>3'::istore -> -1;
ROLLBACK;
BEGIN;
-- operator istore should check existense of a key;
-- ./spec/operator_spec.rb:14;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore ? -1;
SELECT '1=>1, -1=>3'::istore ? 5;
ROLLBACK;
BEGIN;
-- operator istore should add two istores;
-- ./spec/operator_spec.rb:19;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore + '1=>1'::istore;
SELECT '1=>1, -1=>3'::istore + '-1=>-1'::istore;
SELECT '1=>1, -1=>3'::istore + '1=>-1'::istore;
SELECT '1=>NULL, -1=>3'::istore + '1=>-1'::istore;
SELECT '1=>1, -1=>NULL'::istore + '-1=>-1'::istore;
ROLLBACK;
BEGIN;
-- operator istore should add an integer to istore;
-- ./spec/operator_spec.rb:32;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  + 1;
SELECT '-1=>1, 1=>3'::istore  + 1;
SELECT '-1=>1, -1=>3'::istore + 1;
SELECT '1=>1, -1=>3'::istore  + 0;
SELECT '-1=>1, 1=>3'::istore  + 0;
SELECT '-1=>1, -1=>3'::istore + 0;
SELECT '1=>1, -1=>3'::istore  + -1;
SELECT '-1=>1, 1=>3'::istore  + -1;
SELECT '-1=>1, -1=>3'::istore + -1;
ROLLBACK;
BEGIN;
-- operator istore should substract two istores;
-- ./spec/operator_spec.rb:53;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore - '1=>1'::istore;
SELECT '1=>1, -1=>3'::istore - '-1=>-1'::istore;
SELECT '1=>1, -1=>3'::istore - '1=>-1'::istore;
SELECT '1=>NULL, -1=>3'::istore - '1=>-1'::istore;
ROLLBACK;
BEGIN;
-- operator istore should substract integer from istore;
-- ./spec/operator_spec.rb:64;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  - 1;
SELECT '-1=>1, 1=>3'::istore  - 1;
SELECT '-1=>1, -1=>3'::istore - 1;
SELECT '1=>1, -1=>3'::istore  - 0;
SELECT '-1=>1, 1=>3'::istore  - 0;
SELECT '-1=>1, -1=>3'::istore - 0;
SELECT '1=>1, -1=>3'::istore  - -1;
SELECT '-1=>1, 1=>3'::istore  - -1;
SELECT '-1=>1, -1=>3'::istore - -1;
ROLLBACK;
BEGIN;
-- operator istore should multiply two istores;
-- ./spec/operator_spec.rb:85;
CREATE EXTENSION istore;
SELECT '1=>3, 2=>2'::istore * '1=>2, 3=>5'::istore;
SELECT '-1=>3, 2=>2'::istore * '-1=>2, 3=>5'::istore;
SELECT '-1=>3, 2=>2'::istore * '-1=>-2, 3=>5'::istore;
SELECT '-1=>3, 2=>NULL'::istore * '-1=>-2, 3=>5'::istore;
ROLLBACK;
BEGIN;
-- operator istore should multiply istore with integer;
-- ./spec/operator_spec.rb:96;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  * 1;
SELECT '-1=>1, 1=>3'::istore  * 1;
SELECT '-1=>1, -1=>3'::istore * 1;
SELECT '1=>1, -1=>3'::istore  * 0;
SELECT '-1=>1, 1=>3'::istore  * 0;
SELECT '-1=>1, -1=>3'::istore * 0;
SELECT '1=>1, -1=>3'::istore  * -1;
SELECT '-1=>1, 1=>3'::istore  * -1;
SELECT '-1=>1, -1=>3'::istore * -1;
ROLLBACK;
BEGIN;
-- operator device_istore should fetch values;
-- ./spec/operator_spec.rb:119;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>0'::device_istore -> 'mac';
SELECT 'mac=>1, bot=>3'::device_istore -> 'kermit';
ROLLBACK;
BEGIN;
-- operator device_istore should check existense of a key;
-- ./spec/operator_spec.rb:124;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>3'::device_istore ? 'mac';
SELECT 'mac=>1, bot=>3'::device_istore ? 'kermit';
ROLLBACK;
BEGIN;
-- operator device_istore should add two istores;
-- ./spec/operator_spec.rb:129;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>3'::device_istore + 'mac=>1'::device_istore;
SELECT 'mac=>1, bot=>3'::device_istore + 'bot=>-1'::device_istore;
SELECT 'mac=>1, bot=>3'::device_istore + 'mac=>-1'::device_istore;
ROLLBACK;
BEGIN;
-- operator device_istore should add an integer to istore;
-- ./spec/operator_spec.rb:140;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>3'::device_istore  + 1;
SELECT 'bot=>1, mac=>3'::device_istore  + 1;
SELECT 'bot=>1, bot=>3'::device_istore + 1;
SELECT 'mac=>1, bot=>3'::device_istore  + 0;
SELECT 'bot=>1, mac=>3'::device_istore  + 0;
SELECT 'bot=>1, bot=>3'::device_istore + 0;
SELECT 'mac=>1, bot=>3'::device_istore  + -1;
SELECT 'bot=>1, mac=>3'::device_istore  + -1;
SELECT 'bot=>1, bot=>3'::device_istore + -1;
ROLLBACK;
BEGIN;
-- operator device_istore should substract two istores;
-- ./spec/operator_spec.rb:161;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>3'::device_istore - 'mac=>1'::device_istore;
SELECT 'mac=>1, bot=>3'::device_istore - 'bot=>-1'::device_istore;
SELECT 'mac=>1, bot=>3'::device_istore - 'mac=>-1'::device_istore;
SELECT 'mac=>NULL, bot=>3'::device_istore - 'mac=>-1'::device_istore;
ROLLBACK;
BEGIN;
-- operator device_istore should substract integer from istore;
-- ./spec/operator_spec.rb:172;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>3'::device_istore  - 1;
SELECT 'bot=>1, mac=>3'::device_istore  - 1;
SELECT 'bot=>1, bot=>3'::device_istore - 1;
SELECT 'mac=>1, bot=>3'::device_istore  - 0;
SELECT 'bot=>1, mac=>3'::device_istore  - 0;
SELECT 'bot=>1, bot=>3'::device_istore - 0;
SELECT 'mac=>1, bot=>3'::device_istore  - -1;
SELECT 'bot=>1, mac=>3'::device_istore  - -1;
SELECT 'bot=>1, bot=>3'::device_istore - -1;
ROLLBACK;
BEGIN;
-- operator device_istore should multiply two istores;
-- ./spec/operator_spec.rb:193;
CREATE EXTENSION istore;
SELECT 'mac=>3, phone=>2'::device_istore * 'mac=>2, tablet=>5'::device_istore;
SELECT 'bot=>3, phone=>2'::device_istore * 'bot=>2, tablet=>5'::device_istore;
SELECT 'bot=>3, phone=>2'::device_istore * 'bot=>-2, tablet=>5'::device_istore;
ROLLBACK;
BEGIN;
-- operator device_istore should multiply istore with integer;
-- ./spec/operator_spec.rb:205;
CREATE EXTENSION istore;
SELECT 'mac=>1, bot=>3'::device_istore  * 1;
SELECT 'bot=>1, mac=>3'::device_istore  * 1;
SELECT 'bot=>1, bot=>3'::device_istore * 1;
SELECT 'mac=>1, bot=>3'::device_istore  * 0;
SELECT 'bot=>1, mac=>3'::device_istore  * 0;
SELECT 'bot=>1, bot=>3'::device_istore * 0;
SELECT 'mac=>1, bot=>3'::device_istore  * -1;
SELECT 'bot=>1, mac=>3'::device_istore  * -1;
SELECT 'bot=>1, bot=>3'::device_istore * -1;
ROLLBACK;
BEGIN;
-- operator country_istore should fetch values;
-- ./spec/operator_spec.rb:228;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>0'::country_istore -> 'de';
SELECT 'es=>1, de=>3'::country_istore -> 'us';
ROLLBACK;
BEGIN;
-- operator country_istore should check existense of a key;
-- ./spec/operator_spec.rb:234;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>3'::country_istore ? 'de';
SELECT 'es=>1, de=>3'::country_istore ? 'us';
ROLLBACK;
BEGIN;
-- operator country_istore should add two istores;
-- ./spec/operator_spec.rb:239;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>3'::country_istore + 'es=>1'::country_istore;
SELECT 'es=>1, de=>3'::country_istore + 'de=>-1'::country_istore;
SELECT 'es=>1, de=>3'::country_istore + 'es=>-1'::country_istore;
ROLLBACK;
BEGIN;
-- operator country_istore should add an integer to istore;
-- ./spec/operator_spec.rb:249;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>3'::country_istore  + 1;
SELECT 'de=>1, es=>3'::country_istore  + 1;
SELECT 'de=>1, de=>3'::country_istore + 1;
SELECT 'es=>1, de=>3'::country_istore  + 0;
SELECT 'de=>1, es=>3'::country_istore  + 0;
SELECT 'de=>1, de=>3'::country_istore + 0;
SELECT 'es=>1, de=>3'::country_istore  + -1;
SELECT 'de=>1, es=>3'::country_istore  + -1;
SELECT 'de=>1, de=>3'::country_istore + -1;
SELECT 'de=>NULL, de=>3'::country_istore + -1;
ROLLBACK;
BEGIN;
-- operator country_istore should substract two istores;
-- ./spec/operator_spec.rb:272;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>3'::country_istore - 'es=>1'::country_istore;
SELECT 'es=>1, de=>3'::country_istore - 'de=>-1'::country_istore;
SELECT 'es=>1, de=>3'::country_istore - 'es=>-1'::country_istore;
ROLLBACK;
BEGIN;
-- operator country_istore should substract integer from istore;
-- ./spec/operator_spec.rb:281;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>3'::country_istore  - 1;
SELECT 'de=>1, es=>3'::country_istore  - 1;
SELECT 'de=>1, de=>3'::country_istore - 1;
SELECT 'es=>1, de=>3'::country_istore  - 0;
SELECT 'de=>1, es=>3'::country_istore  - 0;
SELECT 'de=>1, de=>3'::country_istore - 0;
SELECT 'es=>1, de=>3'::country_istore  - -1;
SELECT 'de=>1, es=>3'::country_istore  - -1;
SELECT 'de=>1, de=>3'::country_istore - -1;
ROLLBACK;
BEGIN;
-- operator country_istore should multiply two istores;
-- ./spec/operator_spec.rb:302;
CREATE EXTENSION istore;
SELECT 'es=>3, uk=>2'::country_istore * 'es=>2, io=>5'::country_istore;
SELECT 'de=>3, uk=>2'::country_istore * 'de=>2, io=>5'::country_istore;
SELECT 'de=>3, uk=>2'::country_istore * 'de=>-2, io=>5'::country_istore;
ROLLBACK;
BEGIN;
-- operator country_istore should multiply istore with integer;
-- ./spec/operator_spec.rb:311;
CREATE EXTENSION istore;
SELECT 'es=>1, de=>3'::country_istore  * 1;
SELECT 'de=>1, es=>3'::country_istore  * 1;
SELECT 'de=>1, de=>3'::country_istore * 1;
SELECT 'es=>1, de=>3'::country_istore  * 0;
SELECT 'de=>1, es=>3'::country_istore  * 0;
SELECT 'de=>1, de=>3'::country_istore * 0;
SELECT 'es=>1, de=>3'::country_istore  * -1;
SELECT 'de=>1, es=>3'::country_istore  * -1;
SELECT 'de=>1, de=>3'::country_istore * -1;
ROLLBACK;
BEGIN;
-- operator os_name_istore should fetch values;
-- ./spec/operator_spec.rb:334;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>0'::os_name_istore -> 'ios';
SELECT 'android=>1, ios=>3'::os_name_istore -> 'windows';
ROLLBACK;
BEGIN;
-- operator os_name_istore should check existense of a key;
-- ./spec/operator_spec.rb:339;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>3'::os_name_istore ? 'android';
SELECT 'android=>1, ios=>3'::os_name_istore ? 'windows';
ROLLBACK;
BEGIN;
-- operator os_name_istore should add two istores;
-- ./spec/operator_spec.rb:344;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>3'::os_name_istore + 'android=>1'::os_name_istore;
SELECT 'android=>1, ios=>3'::os_name_istore + 'ios=>-1'::os_name_istore;
SELECT 'android=>1, ios=>3'::os_name_istore + 'android=>-1'::os_name_istore;
ROLLBACK;
BEGIN;
-- operator os_name_istore should add an integer to istore;
-- ./spec/operator_spec.rb:353;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>3'::os_name_istore  + 1;
SELECT 'ios=>1, android=>3'::os_name_istore  + 1;
SELECT 'ios=>1, ios=>3'::os_name_istore + 1;
SELECT 'android=>1, ios=>3'::os_name_istore  + 0;
SELECT 'ios=>1, android=>3'::os_name_istore  + 0;
SELECT 'ios=>1, ios=>3'::os_name_istore + 0;
SELECT 'android=>1, ios=>3'::os_name_istore  + -1;
SELECT 'ios=>1, android=>3'::os_name_istore  + -1;
SELECT 'ios=>1, ios=>3'::os_name_istore + -1;
ROLLBACK;
BEGIN;
-- operator os_name_istore should substract two istores;
-- ./spec/operator_spec.rb:374;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>3'::os_name_istore - 'android=>1'::os_name_istore;
SELECT 'android=>1, ios=>3'::os_name_istore - 'ios=>-1'::os_name_istore;
SELECT 'android=>1, ios=>3'::os_name_istore - 'android=>-1'::os_name_istore;
ROLLBACK;
BEGIN;
-- operator os_name_istore should substract integer from istore;
-- ./spec/operator_spec.rb:383;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>3'::os_name_istore  - 1;
SELECT 'ios=>1, android=>3'::os_name_istore  - 1;
SELECT 'ios=>1, ios=>3'::os_name_istore - 1;
SELECT 'android=>1, ios=>3'::os_name_istore  - 0;
SELECT 'ios=>1, android=>3'::os_name_istore  - 0;
SELECT 'ios=>1, ios=>3'::os_name_istore - 0;
SELECT 'android=>1, ios=>3'::os_name_istore  - -1;
SELECT 'ios=>1, android=>3'::os_name_istore  - -1;
SELECT 'ios=>1, ios=>3'::os_name_istore - -1;
SELECT 'ios=>NULL, ios=>3'::os_name_istore - -1;
ROLLBACK;
BEGIN;
-- operator os_name_istore should multiply two istores;
-- ./spec/operator_spec.rb:406;
CREATE EXTENSION istore;
SELECT 'android=>3, windows-phone=>2'::os_name_istore * 'android=>2, windows=>5'::os_name_istore;
SELECT 'ios=>3, windows-phone=>2'::os_name_istore * 'ios=>2, windows=>5'::os_name_istore;
SELECT 'ios=>3, windows-phone=>2'::os_name_istore * 'ios=>-2, windows=>5'::os_name_istore;
ROLLBACK;
BEGIN;
-- operator os_name_istore should multiply istore with integer;
-- ./spec/operator_spec.rb:416;
CREATE EXTENSION istore;
SELECT 'android=>1, ios=>3'::os_name_istore  * 1;
SELECT 'ios=>1, android=>3'::os_name_istore  * 1;
SELECT 'ios=>1, ios=>3'::os_name_istore * 1;
SELECT 'android=>1, ios=>3'::os_name_istore  * 0;
SELECT 'ios=>1, android=>3'::os_name_istore  * 0;
SELECT 'ios=>1, ios=>3'::os_name_istore * 0;
SELECT 'android=>1, ios=>3'::os_name_istore  * -1;
SELECT 'ios=>1, android=>3'::os_name_istore  * -1;
SELECT 'ios=>1, ios=>3'::os_name_istore * -1;
ROLLBACK;
