BEGIN;
-- bigistore operators bigistore should fetch values;
-- ./spec/istore/operator_spec.rb:10;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>0'::bigistore -> -1;
SELECT '1=>1, -1=>3'::bigistore -> -1;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should check existense of a key;
-- ./spec/istore/operator_spec.rb:15;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::bigistore ? -1;
SELECT '1=>1, -1=>3'::bigistore ? 5;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should add two bigistore;
-- ./spec/istore/operator_spec.rb:20;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::bigistore + '1=>1'::bigistore;
SELECT '1=>1, -1=>3'::bigistore + '-1=>-1'::bigistore;
SELECT '1=>1, -1=>3'::bigistore + '1=>-1'::bigistore;
SELECT '1=>0, -1=>3'::bigistore + '1=>-1'::bigistore;
SELECT '1=>1, -1=>0'::bigistore + '-1=>-1'::bigistore;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should add an integer to #{type};
-- ./spec/istore/operator_spec.rb:33;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::bigistore  + 1;
SELECT '-1=>1, 1=>3'::bigistore  + 1;
SELECT '-1=>1, -1=>3'::bigistore + 1;
SELECT '1=>1, -1=>3'::bigistore  + 0;
SELECT '-1=>1, 1=>3'::bigistore  + 0;
SELECT '-1=>1, -1=>3'::bigistore + 0;
SELECT '1=>1, -1=>3'::bigistore  + -1;
SELECT '-1=>1, 1=>3'::bigistore  + -1;
SELECT '-1=>1, -1=>3'::bigistore + -1;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should substract two bigistore;
-- ./spec/istore/operator_spec.rb:54;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::bigistore - '1=>1'::bigistore;
SELECT '1=>1, -1=>3'::bigistore - '-1=>-1'::bigistore;
SELECT '1=>1, -1=>3'::bigistore - '1=>-1'::bigistore;
SELECT '1=>0, -1=>3'::bigistore - '1=>-1'::bigistore;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should substract integer from bigistore;
-- ./spec/istore/operator_spec.rb:65;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::bigistore  - 1;
SELECT '-1=>1, 1=>3'::bigistore  - 1;
SELECT '-1=>1, -1=>3'::bigistore - 1;
SELECT '1=>1, -1=>3'::bigistore  - 0;
SELECT '-1=>1, 1=>3'::bigistore  - 0;
SELECT '-1=>1, -1=>3'::bigistore - 0;
SELECT '1=>1, -1=>3'::bigistore  - -1;
SELECT '-1=>1, 1=>3'::bigistore  - -1;
SELECT '-1=>1, -1=>3'::bigistore - -1;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should multiply two bigistore;
-- ./spec/istore/operator_spec.rb:86;
CREATE EXTENSION istore;
SELECT '1=>3, 2=>2'::bigistore * '1=>2, 3=>5'::bigistore;
SELECT '-1=>3, 2=>2'::bigistore * '-1=>2, 3=>5'::bigistore;
SELECT '-1=>3, 2=>2'::bigistore * '-1=>-2, 3=>5'::bigistore;
SELECT '-1=>3, 2=>0'::bigistore * '-1=>-2, 3=>5'::bigistore;
ROLLBACK;
BEGIN;
-- bigistore operators bigistore should multiply #{type} with integer;
-- ./spec/istore/operator_spec.rb:97;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::bigistore  * 1;
SELECT '-1=>1, 1=>3'::bigistore  * 1;
SELECT '-1=>1, -1=>3'::bigistore * 1;
SELECT '1=>1, -1=>3'::bigistore  * 0;
SELECT '-1=>1, 1=>3'::bigistore  * 0;
SELECT '-1=>1, -1=>3'::bigistore * 0;
SELECT '1=>1, -1=>3'::bigistore  * -1;
SELECT '-1=>1, 1=>3'::bigistore  * -1;
SELECT '-1=>1, -1=>3'::bigistore * -1;
ROLLBACK;
BEGIN;
-- istore operators istore should fetch values;
-- ./spec/istore/operator_spec.rb:10;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>0'::istore -> -1;
SELECT '1=>1, -1=>3'::istore -> -1;
ROLLBACK;
BEGIN;
-- istore operators istore should check existense of a key;
-- ./spec/istore/operator_spec.rb:15;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore ? -1;
SELECT '1=>1, -1=>3'::istore ? 5;
ROLLBACK;
BEGIN;
-- istore operators istore should add two istore;
-- ./spec/istore/operator_spec.rb:20;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore + '1=>1'::istore;
SELECT '1=>1, -1=>3'::istore + '-1=>-1'::istore;
SELECT '1=>1, -1=>3'::istore + '1=>-1'::istore;
SELECT '1=>0, -1=>3'::istore + '1=>-1'::istore;
SELECT '1=>1, -1=>0'::istore + '-1=>-1'::istore;
ROLLBACK;
BEGIN;
-- istore operators istore should add an integer to #{type};
-- ./spec/istore/operator_spec.rb:33;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  + 1;
SELECT '-1=>1, 1=>3'::istore  + 1;
SELECT '-1=>1, -1=>3'::istore + 1;
SELECT '1=>1, -1=>3'::istore  + 0;
SELECT '-1=>1, 1=>3'::istore  + 0;
SELECT '-1=>1, -1=>3'::istore + 0;
SELECT '1=>1, -1=>3'::istore  + -1;
SELECT '-1=>1, 1=>3'::istore  + -1;
SELECT '-1=>1, -1=>3'::istore + -1;
ROLLBACK;
BEGIN;
-- istore operators istore should substract two istore;
-- ./spec/istore/operator_spec.rb:54;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore - '1=>1'::istore;
SELECT '1=>1, -1=>3'::istore - '-1=>-1'::istore;
SELECT '1=>1, -1=>3'::istore - '1=>-1'::istore;
SELECT '1=>0, -1=>3'::istore - '1=>-1'::istore;
ROLLBACK;
BEGIN;
-- istore operators istore should substract integer from istore;
-- ./spec/istore/operator_spec.rb:65;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  - 1;
SELECT '-1=>1, 1=>3'::istore  - 1;
SELECT '-1=>1, -1=>3'::istore - 1;
SELECT '1=>1, -1=>3'::istore  - 0;
SELECT '-1=>1, 1=>3'::istore  - 0;
SELECT '-1=>1, -1=>3'::istore - 0;
SELECT '1=>1, -1=>3'::istore  - -1;
SELECT '-1=>1, 1=>3'::istore  - -1;
SELECT '-1=>1, -1=>3'::istore - -1;
ROLLBACK;
BEGIN;
-- istore operators istore should multiply two istore;
-- ./spec/istore/operator_spec.rb:86;
CREATE EXTENSION istore;
SELECT '1=>3, 2=>2'::istore * '1=>2, 3=>5'::istore;
SELECT '-1=>3, 2=>2'::istore * '-1=>2, 3=>5'::istore;
SELECT '-1=>3, 2=>2'::istore * '-1=>-2, 3=>5'::istore;
SELECT '-1=>3, 2=>0'::istore * '-1=>-2, 3=>5'::istore;
ROLLBACK;
BEGIN;
-- istore operators istore should multiply #{type} with integer;
-- ./spec/istore/operator_spec.rb:97;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  * 1;
SELECT '-1=>1, 1=>3'::istore  * 1;
SELECT '-1=>1, -1=>3'::istore * 1;
SELECT '1=>1, -1=>3'::istore  * 0;
SELECT '-1=>1, 1=>3'::istore  * 0;
SELECT '-1=>1, -1=>3'::istore * 0;
SELECT '1=>1, -1=>3'::istore  * -1;
SELECT '-1=>1, 1=>3'::istore  * -1;
SELECT '-1=>1, -1=>3'::istore * -1;
ROLLBACK;
