BEGIN;
-- operator istore should fetch values;
-- ./spec/operator_spec.rb:9;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>0'::istore -> -1;
SELECT '1=>1, -1=>3'::istore -> -1;
ROLLBACK;
BEGIN;
-- operator istore should check existense of a key;
-- ./spec/operator_spec.rb:14;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore ? -1;
SELECT '1=>1, -1=>3'::istore ? 5;
ROLLBACK;
BEGIN;
-- operator istore should add two istores;
-- ./spec/operator_spec.rb:19;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore + '1=>1'::istore;
SELECT '1=>1, -1=>3'::istore + '-1=>-1'::istore;
SELECT '1=>1, -1=>3'::istore + '1=>-1'::istore;
SELECT '1=>NULL, -1=>3'::istore + '1=>-1'::istore;
SELECT '1=>1, -1=>NULL'::istore + '-1=>-1'::istore;
ROLLBACK;
BEGIN;
-- operator istore should add an integer to istore;
-- ./spec/operator_spec.rb:32;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  + 1;
SELECT '-1=>1, 1=>3'::istore  + 1;
SELECT '-1=>1, -1=>3'::istore + 1;
SELECT '1=>1, -1=>3'::istore  + 0;
SELECT '-1=>1, 1=>3'::istore  + 0;
SELECT '-1=>1, -1=>3'::istore + 0;
SELECT '1=>1, -1=>3'::istore  + -1;
SELECT '-1=>1, 1=>3'::istore  + -1;
SELECT '-1=>1, -1=>3'::istore + -1;
ROLLBACK;
BEGIN;
-- operator istore should substract two istores;
-- ./spec/operator_spec.rb:53;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore - '1=>1'::istore;
SELECT '1=>1, -1=>3'::istore - '-1=>-1'::istore;
SELECT '1=>1, -1=>3'::istore - '1=>-1'::istore;
SELECT '1=>NULL, -1=>3'::istore - '1=>-1'::istore;
ROLLBACK;
BEGIN;
-- operator istore should substract integer from istore;
-- ./spec/operator_spec.rb:64;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  - 1;
SELECT '-1=>1, 1=>3'::istore  - 1;
SELECT '-1=>1, -1=>3'::istore - 1;
SELECT '1=>1, -1=>3'::istore  - 0;
SELECT '-1=>1, 1=>3'::istore  - 0;
SELECT '-1=>1, -1=>3'::istore - 0;
SELECT '1=>1, -1=>3'::istore  - -1;
SELECT '-1=>1, 1=>3'::istore  - -1;
SELECT '-1=>1, -1=>3'::istore - -1;
ROLLBACK;
BEGIN;
-- operator istore should multiply two istores;
-- ./spec/operator_spec.rb:85;
CREATE EXTENSION istore;
SELECT '1=>3, 2=>2'::istore * '1=>2, 3=>5'::istore;
SELECT '-1=>3, 2=>2'::istore * '-1=>2, 3=>5'::istore;
SELECT '-1=>3, 2=>2'::istore * '-1=>-2, 3=>5'::istore;
SELECT '-1=>3, 2=>NULL'::istore * '-1=>-2, 3=>5'::istore;
ROLLBACK;
BEGIN;
-- operator istore should multiply istore with integer;
-- ./spec/operator_spec.rb:96;
CREATE EXTENSION istore;
SELECT '1=>1, -1=>3'::istore  * 1;
SELECT '-1=>1, 1=>3'::istore  * 1;
SELECT '-1=>1, -1=>3'::istore * 1;
SELECT '1=>1, -1=>3'::istore  * 0;
SELECT '-1=>1, 1=>3'::istore  * 0;
SELECT '-1=>1, -1=>3'::istore * 0;
SELECT '1=>1, -1=>3'::istore  * -1;
SELECT '-1=>1, 1=>3'::istore  * -1;
SELECT '-1=>1, -1=>3'::istore * -1;
ROLLBACK;
